# Site settings
title: Vitaliy Krasnoperov - Backend developer and DevOps
tag_text: Vitaliy Krasnoperov
description: I am backend developer and DevOps in Kaliningrad, Russia

url: https://vkrasnoperov.me
enforce_ssl: vkrasnoperov.me

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
